global_seed: 42

dataset_args:
    data_files:
        train: 
          - data/chia/ner-baseline/train.parquet
        eval:
          - data/chia/ner-baseline/eval.parquet
        test:
          - data/chia/ner-baseline/test.parquet

tokenizer_args:
    pretrained_model_name_or_path: michiyasunaga/BioLinkBERT-base

model_args:
    pretrained_model_name_or_path: michiyasunaga/BioLinkBERT-base

collator_args:
    max_length: 256

training_args:
    learning_rate: 5.e-5
    lr_scheduler_type: 'linear'
    num_train_epochs: 3
    max_steps: 0
    max_grad_norm: 1.
    warmup_ratio: 0.1
    weight_decay: 1.e-4
    gradient_accumulation_steps: 1
    per_device_train_batch_size: 6
    per_device_eval_batch_size: 6
    ddp_find_unused_parameters: False
    bf16: True
    fp16: False
    tf32: False
    torch_compile: False
    eval_strategy: 'steps'
    save_strategy: 'no'
    logging_steps: 0.05
    seed: 42
    data_seed: 23
    remove_unused_columns: true
